import Head from 'next/head'

export default function Home() {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main style={{
      width: `1280px`,
      height: `769px`,
      border: `solid black 1px`,
      margin: `10px`,

      background: `linear-gradient(135deg, rgba(255,255,255,1) 0%,rgba(255,255,255,1) 20%, rgba(196,255,255,1) 80%)`,

      position: `relative`,
    }}>

      <div style={{
        fontFamily: `Inter-ExtraBold`,
        fontSize: `80px`,

        position: `absolute`,
        left: `40px`,
        bottom: `40px`,
      }}>
        <div>Full-stack</div>
        <div>Web development</div>
      </div>

      <div style={{
      }}>
        <div style={{
          position: `absolute`,
          right: `100px`,
          top: `50px`,

          width: `700px`,
          height: `550px`,
          border: `solid black 10px`,
          borderRadius: `40px`,

          boxShadow: `20px 20px 50px 5px rgba(0,0,0,0.18)`,

          transform: `perspective(1000px) rotateX(5deg) rotateY(-23deg) rotateZ(7deg)`, // rotateZ(7deg)

          background: `linear-gradient(135deg, rgba(255,255,255,0.2) 0%, rgba(100,255,255,0.6) 100%)`,
        }}>
          <div style={{
            height: `60px`,
            borderBottom: `solid black 7px`,

            display: `flex`,
            alignItems: `center`,
            justifyContent: `right`,
          }}>
            <div style={{
              marginRight: `15px`,
              width: `25px`,
              height: `25px`,
              backgroundColor: `#29CD3F`,
              borderRadius: `50%`,
            }}></div>
            <div style={{
              marginRight: `15px`,
              width: `25px`,
              height: `25px`,
              backgroundColor: `#FABF2F`,
              borderRadius: `50%`,
            }}></div>
            <div style={{
              marginRight: `15px`,
              width: `25px`,
              height: `25px`,
              backgroundColor: `#F56354`,
              borderRadius: `50%`,
            }}></div>
          </div>
          <div style={{ position: `absolute` }}>
            <img
              src='svgs/next-js.svg'
              width={180}
              style={{
                position: `absolute`,
                left: `30px`,
                top: `50px`,
                filter: `drop-shadow(10px 10px 20px rgb(0 0 0 / 0.3))`,
              }}
            />
            <img
              src='svgs/react.svg'
              height={200}
              style={{
                position: `absolute`,
                left: `235px`,
                top: `34px`,
                transform: `rotateZ(1deg)`,
                filter: `drop-shadow(10px 10px 20px rgb(0 0 0 / 0.20))`,
              }}
            />
            <img
              src='svgs/socket-io.svg'
              width={190}
              style={{
                position: `absolute`,
                left: `485px`,
                top: `50px`,
                transform: `rotateZ(-5deg)`,
                filter: `drop-shadow(10px 10px 20px rgb(0 0 0 / 0.25))`,
              }}
            />
            <img
              src='svgs/node-js.svg'
              width={170}
              style={{
                position: `absolute`,
                left: `150px`,
                top: `250px`,
                filter: `drop-shadow(10px 10px 20px rgb(0 0 0 / 0.2))`,
              }}
            />
            <img
              src='svgs/MongoDB_Logomark_SpringGreen.svg'
              height={180}
              style={{
                position: `absolute`,
                left: `430px`,
                top: `260px`,
                filter: `drop-shadow(10px 10px 20px rgb(0 0 0 / 0.35))`,
              }}
            />
          </div>
        </div>
      </div>

    </main>
  </>
}
